backend:
  name: git-gateway
  branch: master

media_folder: source/images
public_folder: /images
publish_mode: editorial_workflow

# pages auto generate
pages: 
  enabled: true
  # over page collection config
  # if fields not set, would use posts fields config
  config:
    label: "页面"
    delete: false
    create: true
    editor:
      preview: true
    # fields: 
# through hexo config over fields
over_format: true
scripts:
  - js/cms/youtube.js
  - js/cms/img.js

# A list of collections the CMS should be able to edit
collections:
  # Used in routes, ie.: /admin/collections/:slug/edit
  - name: "posts"
    # Used in the UI, ie.: "New Post"
    label: "文章"
    folder: "source/_posts" # The path to the folder where the documents are stored
    sort: "date:desc"
    create: true # Allow users to create new documents in this collection
    editor:
      preview: true
    fields: # The fields each document in this collection have
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm:ss", required: false}
      - {label: "修改日期", name: "updated", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", required: false}
      - {label: "标签(支持多个)", name: "tags", widget: "list", required: false}
      - {label: "置顶", name: "sticky", widget: "boolean", default: false, required: false}
      - {label: "封面图片", name: "cover", widget: "image", choose_url: true, default: false, required: false}
      - {label: "描述", name: "description", widget: "text"}
      #- {label: "博客样式(禁用)", name: "layout", widget: "select", options: ["blog", "tags", "categories"], default: "blog", required: false}
      #- {label: "从首页隐藏", name: "hide", widget: "boolean", default: false, required: false}
      #- {label: "分类(禁用)", name: "categories", widget: "list", required: false}
      - {label: "正文", name: "body", widget: "markdown", required: false}
      - {label: "永久链接地址", name: "permalink", widget: "string", required: false}
      - {label: "显示评论", name: "comments", widget: "boolean", default: true, required: false}
